# Generated by Django 5.2.3 on 2025-06-17 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('customers', '0001_initial'),
        ('riders', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customercomplaint',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='riders.riderprofile'),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='vendors.vendorprofile'),
        ),
        migrations.AddField(
            model_name='customerfavorite',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.gasproduct'),
        ),
        migrations.AddField(
            model_name='customerfavorite',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='vendors.vendorprofile'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerpaymentmethod',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='customers.customerprofile'),
        ),
        migrations.AddField(
            model_name='customerfavorite',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='customers.customerprofile'),
        ),
        migrations.AddField(
            model_name='customercylinder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cylinders', to='customers.customerprofile'),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='customers.customerprofile'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customerprofile'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['customer_type'], name='customers_p_custome_67515c_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['membership_tier'], name='customers_p_members_c465bb_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['total_orders'], name='customers_p_total_o_540702_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpaymentmethod',
            index=models.Index(fields=['customer', 'is_default'], name='customers_p_custome_0347f2_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpaymentmethod',
            index=models.Index(fields=['payment_type'], name='customers_p_payment_98eefb_idx'),
        ),
        migrations.AddIndex(
            model_name='customerfavorite',
            index=models.Index(fields=['customer', 'favorite_type'], name='customers_f_custome_f145c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerfavorite',
            unique_together={('customer', 'product'), ('customer', 'vendor')},
        ),
        migrations.AddIndex(
            model_name='customercylinder',
            index=models.Index(fields=['customer', 'status'], name='customers_c_custome_d01aab_idx'),
        ),
        migrations.AddIndex(
            model_name='customercylinder',
            index=models.Index(fields=['serial_number'], name='customers_c_serial__081a32_idx'),
        ),
        migrations.AddIndex(
            model_name='customercylinder',
            index=models.Index(fields=['status'], name='customers_c_status_bd1383_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['customer', 'status'], name='customers_c_custome_619a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['complaint_type', 'status'], name='customers_c_complai_e34222_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['priority', 'status'], name='customers_c_priorit_f02b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraddress',
            index=models.Index(fields=['customer', 'is_default'], name='customers_a_custome_d08d94_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraddress',
            index=models.Index(fields=['address_type'], name='customers_a_address_8a01e9_idx'),
        ),
    ]
